### ISSUE TITLE
[1.14.4] No config file being generated, crash when trying to create world

### ISSUE THREAD

**Issue by Mantarri** [The-Fireplace-Minecraft-Mods/Block-Replacer#11]
Forge version: 1.14.4-28.1.76

Mod version: 1.14.4-2.1.1
Mods List: Worldgen Block Replacer
[latest.log](https://paste.ubuntu.com/p/DtcwwWH2SH/)
[debug.log](https://paste.ubuntu.com/p/tJCD5jqykb/)
[crash report](https://paste.ubuntu.com/p/hctHYqDpvD/)
What I did:
Attempted to create a world, and load it.

What happened:
The game crashed when attempting to load the world, saying that there was not a valid config file
What I tried:
Checking in configs/, and saves/MySave/serverconfigs/ for a config file
I did not find a config in either folder, so I tried creating both a `wgblockreplacer.cfg`, and a `wgblockreplacer.toml` containing the contents of [this example config on your CF page](https://paste.ubuntu.com/p/TsP2FZHp5t/), but to no avail.

**Comment by Partonetrain** [comment]
it's `worldgenblockreplacer-server.toml` in saves/MySave/serverconfigs/ . Looks like that example config is for 1.12 or earlier, so don't use it.

I'm having trouble with the config too though - https://github.com/The-Fireplace-Minecraft-Mods/Block-Replacer/issues/12

**Comment by The-Fireplace** [comment]
Your initial config is set to replace stone with stone, which then shuts down the server because it assumes that was a configuration error that you'll want to correct _before_ generating the world. Right before the crash, in the latest.log:
`WorldGen Block Replacer is improperly configured. The replacement for (0) is itself.`
And the crash itself says `WorldGen Block Replacer is improperly configured, shutting down. See the logs to find out what wasn't configured properly.`
EDIT: And as Partonetrain said, the config is found in the world's serverconfigs folder now.

**Comment by Mantarri** [comment]
Ah, thank you, maybe you could change the Curseforge page to reflect these changes, this really threw me for a loop.
