### ISSUE TITLE
Replacing Ores

### ISSUE THREAD

**Issue by SeptJack** [The-Fireplace-Minecraft-Mods/Block-Replacer#18]
I've tried replacing all ores in the overworld except quartz with their respective pure blocks and I load the world and no crashes occur so the config is obviously not incorrect because I have it set to crash with incorrect configs then I look in the world but the ores aren't replaced. Thanks

**Comment by The-Fireplace** [comment]
Have you tried setting the `lateReplacement` config option to a larger value, such as 2 or 3?

**Comment by SaltSouls** [comment]
> Have you tried setting the `lateReplacement` config option to a larger value, such as 2 or 3?

I hate to reopen a seemingly dead thread, but I'm having the same issues. I have the late ore replacement up to like 5, but am still finding large sections of ores that haven't been replaced. It almost seems like it is trying to replace the ores in the chunks before they finish generating and because of that it can't find the ores to replace. I have noticed that in chunks that have already generated, that it doesn't have an issue, but new chunks run into large quantities of missed ores.

**Comment by The-Fireplace** [comment]
> > Have you tried setting the `lateReplacement` config option to a larger value, such as 2 or 3?
> 
> I hate to reopen a seemingly dead thread, but I'm having the same issues. I have the late ore replacement up to like 5, but am still finding large sections of ores that haven't been replaced. It almost seems like it is trying to replace the ores in the chunks before they finish generating and because of that it can't find the ores to replace. I have noticed that in chunks that have already generated, that it doesn't have an issue, but new chunks run into large quantities of missed ores.

Is this happening with vanilla ores or modded ores?

**Comment by SaltSouls** [comment]
> Is this happening with vanilla ores or modded ores?

This is happening with modded ores. I don't know if this mod was supposed to be able to handle them or not, but lots of the modded ores, like for instance the several types of copper, are not being properly replaced. I know that nothing is wrong in the config and I tried to extend the time at which it looks for said things, but to no avail.
Feel free to look at my config if you think the issue lies in there: [config file](https://hastebin.com/vizeyopili.yaml)
P.S: Yes the mod works when it retrogens chunks, but it struggles and often fails when generating new ones.

**Comment by The-Fireplace** [comment]
I believe you, the mods are probably running their worldgen after this replacement happens. I tried making the replacement happen a bit later in the process to hopefully avoid this problem, but odds are it won't ever cover 100% of cases. Still, I'll take another look and see if I can get it to happen later than it already does

**Comment by SaltSouls** [comment]
> I believe you, the mods are probably running their worldgen after this replacement happens. I tried making the replacement happen a bit later in the process to hopefully avoid this problem, but odds are it won't ever cover 100% of cases. Still, I'll take another look and see if I can get it to happen later than it already does

Would you like a modlist to attempt this with as a base of reference for the timings? The config I have is using several ones that I think would be good ones to test with at the very least.

**Comment by The-Fireplace** [comment]
Just one mod that it isn't working for should be good, I don't want to go digging through a full mod list to find what does and doesn't work

**Comment by SaltSouls** [comment]
> Just one mod that it isn't working for should be good, I don't want to go digging through a full mod list to find what does and doesn't work

I would say either test with Railcraft or Embers(if you are choosing from my mods list). Railcraft would probably be the best choice though.
